# --- Backend URL ---
BACKEND_URL = "https://asmarahman-meal-planner-backend.hf.space"

# --- Hugging Face API ---
HF_TOKEN = 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

# --- Observability ---
LANGFUSE_PUBLIC_KEY=pk-lf-8408fc19-56d2-4010-b7ec-1ebb22db20d6
LANGFUSE_SECRET_KEY=sk-lf-0cbb1f83-6c28-41fc-af89-317064275ca5
LANGFUSE_HOST = "https://cloud.langfuse.com"
